@startuml
allow_mixing
skinparam RoundCorner 15
skinparam BackgroundColor lightGray
skinparam AgentBorderColor Yellow
skinparam DefaultFontColor black
skinparam DefaultFontSize 25
left to right direction

' skinparam 

folder feedbackloops #LightGoldenRodYellow {
    control parents2Academy #aliceblue
    control Academy2DFE #red
    control AcademyOtherStakeholders #Fuchsia
}

node DigitalAcademy #9999ff{
    portin connect
    portout tomarket
    portout tosubscribers
    
    database SkillsOnBelt[
    DataAnalytics like BI,looker,execl++,powerbi,tableau
    ====
    ArtificialIntelligence 
    ----
    DeepLearning-rnn,generative AI
    ====
    blockchain-DLT
    ===
    Algorithms & models
    ===
    horizon TECHNOLOGY like quantum,optimizers,stable diffusion
    ===
    Public cloud & tools gcp,azure,aws
    ---
    low code platforms
    ===
    Robotics
    ===
    cybersecurity,networking & OWSAP
    ===
    ...other skills
    ===
]

}
feedbackloops ---> connect: <:tent:>


artifact deliverable #green;line:blue{
    class certification {
        name
        date
    }
    Json projectBased #lightblue{
        "name":"student",
        "Title":"project outcome",
        "teams":["Team1","Team2"]
    } 

}

tosubscribers <-(0)->deliverable : outcome <:fire:>


@enduml
